Exam/src/music/models/Product.java
package music.models;


import java.io.Serializable;
import java.text.NumberFormat;

public class Product implements Serializable {
    private static final long serialVersionUID = 1L;
    
    private String code;
    private String description;
    private double price;

    public Product() {}

    public Product(String code, String description, double price) {
        this.code = code;
        this.description = description;
        this.price = price;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public double getPrice() {
        return price;
    }

    public String getPriceCurrencyFormat() {
        NumberFormat currency = NumberFormat.getCurrencyInstance();
        return currency.format(price);
    }

    public String getImageURL() {
        String imageURL = "/musicStore/images/" + code + "_cover.jpg";
        return imageURL;
    }

    public String getProductType() {
        return "Audio CD";
    }
}

Exam/src/music/controller/DeleteProductServlet.java
package music.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import music.data.ProductDB;
import music.models.Product;

@WebServlet("/deleteProduct")
public class DeleteProductServlet extends MusicServlet {
    private static final long serialVersionUID = 1L;

    private static final String PAGE_URL = "/WEB-INF/delete_product.jsp";

    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        handleHeader(req);

        HttpSession session = req.getSession();
        final Object sessionLock = session.getId().intern();

        String productCode = req.getParameter("productCode");

        String message;
        synchronized (sessionLock) {
            Product product = (Product)retrieveSessionAttribute(req, "deleteProduct");
            if (product == null || productCode == null || !product.getCode().equals(productCode)) {
                message = getMessage("ACTION_CANCELLED");
            } else {
                ProductDB.deleteProduct(product);
                message = getMessage("PRODUCT_DELETED", product.getCode());
            }
        }

        redirectToDisplayProducts(req, resp, message);
    }

    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        handleHeader(req);

        String productCode = req.getParameter("productCode");
        Product product = ProductDB.getProduct(productCode);

        req.getSession().setAttribute("deleteProduct", product);
        req.setAttribute("product", product);

        forwardUrl(req, resp, PAGE_URL);
    }
}

Exam/src/music/controller/DisplayProductsServlet.java
package music.controller;

import java.io.IOException;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebInitParam;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import music.data.Messages;
import music.data.ProductDB;

@WebServlet(
    urlPatterns = "/displayProducts",
    initParams = { @WebInitParam(name = "messagesFilePath", value = "/WEB-INF/messages.txt") }
)
public class DisplayProductsServlet extends MusicServlet {
    private static final long serialVersionUID = 1L;

    private static final String PAGE_URL = "/WEB-INF/display_products.jsp";

    @Override
    public void init(ServletConfig config) throws ServletException {
        super.init(config);

        String relativePath = config.getInitParameter("messagesFilePath");
        String filePath = getServletContext().getRealPath(relativePath);
        Messages messages = new Messages(filePath);
        getServletContext().setAttribute("messages", messages);
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        handleHeader(req);

        req.setAttribute("productList", ProductDB.getProducts());

        forwardUrl(req, resp, PAGE_URL);
    }
}

Exam/src/music/controller/UpdateProductServlet.java
package music.controller;

import java.io.IOException;
import java.math.BigDecimal;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import music.models.Product;

public abstract class UpdateProductServlet extends MusicServlet {
    private static final long serialVersionUID = 1L;

    private static final String PAGE_URL = "/WEB-INF/update_product.jsp";

    private int productCodeMaxLength;
    private int productDescriptionMaxLength;
    private int productPriceMaxLength;
    private double productPriceMaxValue;

    @Override
    public void init() {
        ServletContext context = getServletContext();

        productPriceMaxValue = Double.parseDouble(context.getInitParameter("productPriceMaxValue"));
        
        productCodeMaxLength = Integer.parseInt(context.getInitParameter("productCodeMaxLength"));
        productDescriptionMaxLength = Integer.parseInt(context.getInitParameter("productDescriptionMaxLength"));
        productPriceMaxLength = String.format("%.2f", productPriceMaxValue).length();
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        handleHeader(req);

        String code = req.getParameter("productCode");
        String description = req.getParameter("productDescription");
        String price = req.getParameter("productPrice");

        HttpSession session = req.getSession();
        final Object sessionLock = session.getId().intern();

        synchronized (sessionLock) {
            try {
                Product product = createProduct(code, description, price);
                String message = performRequestAction(req, product);

                removeSessionAttributes(req);
                redirectToDisplayProducts(req, resp, message);
            } catch (IllegalStateException e) {
                removeSessionAttributes(req);
                redirectToDisplayProducts(req, resp, e.getMessage());
            } catch (IllegalArgumentException e) {
                setRequestAttributes(req, code, description, price);
                forwardUrl(req, resp, PAGE_URL, e.getMessage());
            }
        }
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        handleHeader(req);
        forwardUrl(req, resp, PAGE_URL);
    }

    protected void setRequestAttributes(
        HttpServletRequest req,
        String productCode,
        String productDescription,
        String productPrice
    )
    {
        req.setAttribute("updateProductAction", req.getContextPath() + req.getServletPath());
        req.setAttribute("productCode", truncateString(productCode, productCodeMaxLength));
        req.setAttribute("productDescription", truncateString(productDescription, productDescriptionMaxLength));
        req.setAttribute("productPrice", productPrice);

        req.setAttribute("productCodeMaxLength", productCodeMaxLength);
        req.setAttribute("productDescriptionMaxLength", productDescriptionMaxLength);
        req.setAttribute("productPriceMaxLength", productPriceMaxLength);

        req.setAttribute("productCodeRequired", true);
        req.setAttribute("productCodeReadonly", false);
    }

    protected void removeSessionAttributes(HttpServletRequest req) {

    }

    protected abstract String performRequestAction(HttpServletRequest req, Product product);

    private Product createProduct(String code, String description, String price) {
        if (code == null || code.isEmpty()) {
            throw new IllegalArgumentException(getMessage("MISSING_PRODUCT_CODE"));
        } else if (code.length() > productCodeMaxLength) {
            throw new IllegalArgumentException(getMessage("PRODUCT_CODE_TOO_LONG", productCodeMaxLength));
        }

        if (description == null || description.isEmpty()) {
            throw new IllegalArgumentException(getMessage("MISSING_PRODUCT_DESCRIPTION"));
        } else if (description.length() > productDescriptionMaxLength) {
            throw new IllegalArgumentException(getMessage("PRODUCT_DESCRIPTION_TOO_LONG", productDescriptionMaxLength));
        }

        if (price == null || price.isEmpty()) {
            throw new IllegalArgumentException(getMessage("MISSING_PRODUCT_PRICE"));
        }

        BigDecimal parsedPrice = null;
        try {
            parsedPrice = new BigDecimal(price);
        } catch (Exception e) {
            parsedPrice = new BigDecimal(-1);
        }
        double priceValue = parsedPrice.doubleValue();
        boolean validPrice = parsedPrice.scale() <= 2 && priceValue >= 0;

        if (!validPrice) {
            throw new IllegalArgumentException(getMessage("INVALID_PRODUCT_PRICE", price));
        }
        if (priceValue >= productPriceMaxValue) {
            throw new IllegalArgumentException(getMessage("PRODUCT_PRICE_TOO_HIGH", price, productPriceMaxValue));
        }

        return new Product(code, description, priceValue);
    }

    private static String truncateString(String str, int length) {
        if (str == null || str.length() < length) {
            return str;
        }
        return str.substring(0, length);
    }
}

Exam/WebContent/WEB-INF/delete_product.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<c:import url="/WEB-INF/header.jsp">
    <c:param name="heading" value="Are you sure you want to delete this product?" />
</c:import>

<span class="label">Code:</span>
<span id="productCode">${fn:escapeXml(product.code)}</span>
<br>

<span class="label">Description:</span>
<span id="productDescription">${fn:escapeXml(product.description)}</span>
<br>

<span class="label">Price:</span>
<span id="productPrice">${fn:escapeXml(product.priceCurrencyFormat)}</span>
<br>

<form action="deleteProduct" method="post">
    <input type="hidden" name="productCode" value="${fn:escapeXml(product.code)}">
    <input type="submit" value="Yes">
</form>
<form action="displayProducts" method="get">
    <input type="submit" value="No">
</form>

<c:import url="/WEB-INF/footer.jsp" />

Exam/WebContent/WEB-INF/display_products.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<c:import url="/WEB-INF/header.jsp">
    <c:param name="heading" value="Products" />
</c:import>

<table>
    <tr>
        <th>Code</th>
        <th>Description</th>
        <th>Price</th>
        <th></th>
        <th></th>
    </tr>
    <c:forEach var="product" items="${productList}">
        <tr>
            <td>${fn:escapeXml(product.code)}</td>
            <td>${fn:escapeXml(product.description)}</td>
            <td>${fn:escapeXml(product.priceCurrencyFormat)}</td>
            <td>
                <a href="editProduct?productCode=${fn:escapeXml(product.code)}">Edit</a>
            </td>
            <td>
                <a href="deleteProduct?productCode=${fn:escapeXml(product.code)}">Delete</a>
            </td>
        </tr>
    </c:forEach>
</table>
<form action="addProduct" method="get">
    <input type="submit" value="Add Product">
</form>

<c:import url="/WEB-INF/footer.jsp" />

Exam/WebContent/WEB-INF/footer.jsp
</body>
</html>

Exam/WebContent/WEB-INF/header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Product Maintenance</title>
<link rel="stylesheet" href="styles/main.css">
</head>
<body>

    <h1>${fn:escapeXml(param.heading)}</h1>

    <div id="alert" class="alert">${fn:escapeXml(message)}</div>

Exam/WebContent/WEB-INF/index.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<c:import url="/WEB-INF/header.jsp">
    <c:param name="heading" value="Product Maintenance" />
</c:import>

<a href="./displayProducts">View Products</a>

<c:import url="/WEB-INF/footer.jsp" />

Exam/WebContent/WEB-INF/update_product.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="music" uri="/WEB-INF/music.tld"%>

<c:import url="/WEB-INF/header.jsp">
    <c:param name="heading" value="Product" />
</c:import>

<p>
    <span class="required"></span>
    marks required fields
</p>
<form action="${updateProductAction}" method="post">
    <music:labeledInput id="productCode" value="${fn:escapeXml(productCode)}" size="8"
        maxLength="${productCodeMaxLength}" required="${productCodeRequired}" readonly="${productCodeReadonly}">Code:</music:labeledInput>
    <br>

    <music:labeledInput id="productDescription" value="${fn:escapeXml(productDescription)}" size="64"
        maxLength="${productDescriptionMaxLength}" required="true">Description:</music:labeledInput>
    <br>

    <music:labeledInput id="productPrice" value="${fn:escapeXml(productPrice)}" size="8"
        maxLength="${productPriceMaxLength}" required="true">Price:</music:labeledInput>
    <br>

    <span class="label">&nbsp;</span>
    <input type="submit" value="Update Product">
</form>
<form action="displayProducts" method="get">
    <input type="submit" value="View Products">
</form>

<c:import url="/WEB-INF/footer.jsp" />